cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

jdk:
  - oraclejdk8

scala:
   - 2.11.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

notifications:
  email:
    - thorben@stangenberg.ch